site_name: 深度开发文档
site_url: http://docs.deepin.io/

#theme: readthedocs
theme_dir: theme/dmkdocs
repo_url: https://github.com/Iceyer/docs.iceyer.net/

#include_search: true

copyright: Copyright &copy; 2015, Deepin

pages:
    - ['index.md', '首页', '']
    - ['guide/start.md', '文档服务', '编写指南']
    - ['api/rest.md', 'DeepinID', '接口设计']
    - ['api/oauth2.md', 'DeepinID', 'OAuth2接口']
