site_name: Deepin Developer Documents

#theme: readthedocs
theme_dir: theme/dmkdocs

pages:
    # Home
     - ['index.md', '首页']
    # # Design 
     - ['design/authentication.md', '设计方案', '单点登录']
     - ['design/sync-state.md', '设计方案', '状态同步接口']
    # # Develop Guide
     - ['api/rest.md', '接口文档', '接口设计']
     - ['api/oauth2.md', '接口文档', '登录认证']
     - ['api/user.md', '接口文档', '用户管理']
    #
